### ISSUE TITLE
오류들

### ISSUE THREAD

**Issue by sfhk1234** [jaycho1214/DIV2CSU#3]
![asdfasdg](https://github.com/jaycho1214/DIV2CSU/assets/118529644/fc878f2c-1e9b-4fb5-bf61-c461810059a4)
용사
-상점 관리-
- [x] 잔여상점/총상점/총벌점 순서 바뀜
ex)60/30/-30순으로 표기

-상점 요청-
- [x] 상점 템플릿에 있는 숫자 버튼 눌러서 요청하면 상점칸에 숫자는 들어가 있지만 '상벌점은 최소 1점입니다'오류 출력/이후 상점칸 숫자를 지우고 아무 숫자를 입력해도 같은 오류 출력
- [x] 보급,의무중대 상점 템플릿에 있는 '시효성 물자...'칸이 제목이 길어서 숫자 버튼이 안보임(상점 부여도 마찬가지)

간부(대대장 계정)
-상점 사용-
- [x] 상점을 입력해도 '상벌점은 최소 1점입니다'에러 출력(상점 부여도 동일)

로그인
- [x] 현재 로그인 한 상태에서 로그아웃한 후 새로고침을 하지 않고 아무 계정이나 로그인을 시도하면 무한로딩이 걸림

**Comment by jaycho1214** [comment]
다 고침
