### ISSUE TITLE
로그인창 복사버그

### ISSUE THREAD

**Issue by sfhk1234** [jaycho1214/DIV2CSU#4]
![캡처](https://github.com/jaycho1214/DIV2CSU/assets/118529644/4ca5c04c-6bfc-4ca7-859f-c7082cfaa3c3)

**Comment by jaycho1214** [comment]
[div2csu-ot7k1hz2m-div-2-csu.vercel.app](https://vercel.live/link/div2csu-ot7k1hz2m-div-2-csu.vercel.app?via=deployment-domains-list-commit)

여기다가 올리는중 확인점
